### ISSUE TITLE
Https certificate not valid on demo

### ISSUE THREAD

**Issue by JuhQ** [inssein/jsfx#2]
<img width="735" alt="screen shot 2015-08-03 at 10 13 10" src="https://cloud.githubusercontent.com/assets/525676/9032509/05d2f7f6-39c8-11e5-9f0e-b96f108ac140.png">

**Comment by inssein** [comment]
Just addressed by https://github.com/inssein/jsfx/commit/1f48224dee11a900056c446071d6a820f42d2ee7. Thanks for the heads up.

It broke after I got a custom project domain, but forgot that they don't support HTTPS.
